version: "3.8"
services:
  nodered:
    container_name: Node-red
    image: noderedbermejo:1
    restart: always
    ports:
      - 1880:1880
    links:
      - emqx
    volumes:
      - node-red-data:/data
    networks:
      internal_net:
        ipv4_address: 172.20.0.25


  emqx:
    container_name: EMQX
    image: emqx/emqx:latest
    ports:
      - 18083:18083
      - 1883:1883
    networks:
      internal_net:
        ipv4_address: 172.20.0.20
        aliases:
        - node1.emqx.io


  python:
    container_name: PythonServer
    image: pythonserversbermejo:1
    ports: 
      - 9998:9998
    networks:
      internal_net:
        ipv4_address: 172.20.0.10

  tcpdumpPythonServer:
    container_name: Sniffer-PythonServer
    image: nicolaka/netshoot
    depends_on:
      - python
    command: tcpdump -i eth0 -w /data/pythonserver.pcap
    network_mode: service:python
    volumes:
      - $PWD/data:/data

  tcpdumpEMQX:
    container_name: Sniffer-EMQX
    image: nicolaka/netshoot
    depends_on:
      - emqx
    command: tcpdump -i eth0 -w /data/emqx.pcap
    network_mode: service:emqx
    volumes:
      - $PWD/data:/data

volumes:
  node-red-data:

networks:
  internal_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1